### ISSUE TITLE
Sound issues when playing on a real DSi when frame_speed or bgm_frame_speed is not set to 8

### ISSUE THREAD

**Issue by Ganguuu** [khang06/dsiflipencode#3]
As the title says, this issue happens when frame_speed or bgm_frame_speed is not set to 8. Issues that happen vary, but I've found two main problems that may happen:

- frame_speed and/or bgm_frame_speed will not be set as what they were intended to be; sometimes one will be set to the other
- The BGM will be instead assigned to sound effect 1; since there is no corresponding frame speed for sound effects, the sound effects will play as if their frame speed is equal to the flipnote's frame speed

These issues only happen on a real DSi; custom flipnote players will play the flipnote as intended.

Problem seems to be caused by some sort of a misalignment in the sound header, as these issues only have to do with parts of the sound header, and the issue can seemingly be manually fixed by shifting around values in the sound header (though this tends to mess up playback on custom players). I haven't found a consistent manual fix.

It should be noted that I'm doing this on firmware version 1.4U. It's possible version 1.4.5U fixes this issue, but I haven't had time to try that out yet.

EDIT: Probably should've also mentioned this is happening with release version 1.0.1.

**Comment by khang06** [comment]
that's really strange, i thought i fixed that when i moved the encoded flag... honestly i didn't actually test changing frame speeds that much because every test flipnote i made was frame speed 8 and bgm speed 8. what custom flipnote players did you test on?

**Comment by Ganguuu** [comment]
I've mainly been using https://flipnote.rakujira.jp/, but there are 1 or 2 "fixed" (but not really because I only fixed it for DSi so it's broken everywhere else) flipnotes I put on Sudomemo and played through Sudomemo Theatre, like this one: https://www.sudomemo.net/watch/F86973_1229141BB2FC9_000

**Comment by jaames** [comment]
Hey @Ganguuu, please could you share a couple of sample .PPMs that have this issue?

I'm the author of Flipnote Player, as well as the Flipnote converter used on Sudomemo Theatre. It's really odd if only one will correctly parse the Flipnote, IIRC they both use the same logic to handle the alignment thing going on with the sound header

**Comment by Ganguuu** [comment]
@jaames https://drive.google.com/file/d/1q2gxZn9lQ8lrBl1Fn9eCvNN_UN6mbp8U/view?usp=sharing
Here's one at a frame speed of 8, and a BGM frame speed of 6; it'll play fine on the online player, but the DSi will have the "sound effect 1" issue.

**Comment by jaames** [comment]
As far as we know, the sound header offset is calculated as `1696 + frame data length + frame count` but for alignment purposes it's always rounded up to the nearest multiple of 4. 

According to that rule, your Flipnote's sound header should be at offset `158040` (rounded up from `158038`), and that seems to be the case. If the BGM track is assigned to SE1 in Flipnote Studio then this would suggest that the DSi starts reading the sound header at `158036` though, which is kinda weird.

I'll investigate further, but part of me wonders if the app calculates the sound header offset slightly differently, or maybe some other part of the file is messed up and that's affecting it in a weird way

**Comment by khang06** [comment]
i didn't have anything to do today so i looked into this and (hopefully) fixed it with f39298b

**Comment by EpicLPer** [comment]
I just had the same issue on a PPM which plays fine on hardware but has the sound assigned to "Sound 1" instead of the BGM channel. The BGM and Playback speed in my config however are both set to 8.

**Comment by khang06** [comment]
fixed *for real* this time

**Comment by arceuss** [comment]
how did u get it on dsi tho wtf !!

**Comment by Ganguuu** [comment]
magic

**Comment by RinLovesYou** [comment]
the power of god and anime
