### ISSUE TITLE
I do get it but I don't understand the thumbnail.bin thing

### ISSUE THREAD

**Issue by TuxPenguin09** [khang06/dsiflipencode#4]
According to your README.md file
`a thumbnail.bin can be grabbed from a flipnote by copying 0x600 bytes at 0xA0, but making a 0x600 byte file filled with zeros works too`
and I don't understand how to grab a flipnote like were to copy that 0x600 bytes at 0xA0 thing.
But yeah, I sometimes get this error like I converted my 64 x 48 image file to `thumbnail.bin` but this shows up:
`Encoder threw an exception: thumbnail.bin isn't 0x600 bytes long!`
I tried to research and search for everything, sorry but I'm not a hacker to edit some hax in it.

**Comment by khang06** [comment]
send your thumbnail.bin, you probably did something wrong

**Comment by TuxPenguin09** [comment]
well, I did something wrong probably.
[thumbnail.bin.zip](https://github.com/khang06/dsiflipencode/files/5591879/thumbnail.bin.zip)

**Comment by khang06** [comment]
yeah your file is 397 bytes instead of 1536 bytes long. in a hex editor you basically just do this
![image](https://user-images.githubusercontent.com/11239786/100141347-49831e80-2e60-11eb-98e8-421122737e8f.png)
with a 0x600 byte long selection and paste it into a new file

**Comment by TuxPenguin09** [comment]
Okay thanks, it actually works, also your tool is great!
